/**
 * seedDatabase.js
 * Run: node backend/services/seedDatabase.js
 * Seeds MongoDB with 10 real Indian government welfare schemes.
 */

require("dotenv").config();
const mongoose = require("mongoose");
const Scheme = require("../models/Scheme");

const SCHEMES = [
  {
    slug: "pm-kisan",
    name: "PM-KISAN Samman Nidhi",
    nameHindi: "पीएम किसान सम्मान निधि",
    tagline: "₹6,000 per year directly to farmers",
    category: "farmer",
    ministry: "Ministry of Agriculture & Farmers Welfare",
    icon: "🌾",
    bgColor: "#FEF3C7",
    shortDescription: "Direct income support of ₹6,000 per year to small and marginal farmers in three equal instalments.",
    whatIsIt: "PM-KISAN provides financial support of ₹6,000 per year to all land-holding farmer families across India. The money comes in three instalments of ₹2,000 each, directly into the farmer's bank account. This helps farmers meet agricultural and household needs.",
    benefits: ["₹6,000/year in 3 instalments of ₹2,000 each", "Direct bank transfer (DBT) — no middlemen", "Applicable from Kharif 2018 onwards"],
    documents: ["Aadhaar card", "Land records (khatauni/patta)", "Bank passbook with IFSC", "Mobile number linked to Aadhaar"],
    howToApply: ["Visit pmkisan.gov.in", "Click 'New Farmer Registration'", "Enter Aadhaar number and state", "Fill in land details and bank account", "Submit — local patwari will verify", "Once verified, receive first instalment in 2-4 weeks"],
    eligibilityRules: {
      logic: "AND",
      conditions: [
        { field: "income", operator: "lte", value: 200000, label: "Annual income up to ₹2,00,000" },
        { field: "occupation", operator: "eq", value: "Farmer", label: "Must be a farmer" },
        { field: "age", operator: "gte", value: 18, label: "Age 18 or above" },
      ],
    },
    eligibilityText: "Small and marginal farmers with annual income up to ₹2 lakh",
    officialLink: "https://pmkisan.gov.in",
    applyLink: "https://pmkisan.gov.in/RegistrationFormNew.aspx",
  },
  {
    slug: "national-scholarship-portal",
    name: "National Scholarship Portal",
    nameHindi: "राष्ट्रीय छात्रवृत्ति पोर्टल",
    tagline: "Scholarships for students from ₹1,000 to ₹1.2L/year",
    category: "student",
    ministry: "Ministry of Education",
    icon: "📚",
    bgColor: "#EDE9FE",
    shortDescription: "Central portal for 30+ scholarship schemes covering school, college, and professional courses for students from low-income families.",
    whatIsIt: "NSP is a one-stop platform for all central government scholarships. It covers Pre-Matric, Post-Matric, and Merit-cum-Means scholarships for SC, ST, OBC, Minority, and EWS students. Benefits range from ₹1,000/year for school students to ₹1.2 lakh/year for professional courses.",
    benefits: ["Pre-Matric: ₹1,000–₹7,000/year", "Post-Matric: up to ₹1.2 lakh/year", "Tuition fees + maintenance allowance", "Direct payment to student's bank account"],
    documents: ["Aadhaar card", "School/college enrollment certificate", "Previous year marksheet", "Income certificate (family income proof)", "Caste certificate (if applicable)", "Bank passbook"],
    howToApply: ["Register at scholarships.gov.in", "Select your scholarship scheme", "Fill in academic and income details", "Upload required documents", "Submit before deadline (usually October-November)", "Track status on the portal"],
    eligibilityRules: {
      logic: "AND",
      conditions: [
        { field: "occupation", operator: "eq", value: "Student", label: "Must be a student" },
        { field: "income", operator: "lte", value: 500000, label: "Family income up to ₹5 lakh" },
        { field: "age", operator: "lte", value: 30, label: "Age 30 or below" },
      ],
    },
    eligibilityText: "Students enrolled in school or college with family income below ₹5 lakh",
    officialLink: "https://scholarships.gov.in",
    applyLink: "https://scholarships.gov.in/fresh/loginPage",
  },
  {
    slug: "pm-awas-yojana",
    name: "PM Awas Yojana – Urban",
    nameHindi: "प्रधानमंत्री आवास योजना",
    tagline: "Home loan subsidy up to ₹2.67 lakh for your own house",
    category: "housing",
    ministry: "Ministry of Housing & Urban Affairs",
    icon: "🏠",
    bgColor: "#DCFCE7",
    shortDescription: "Interest subsidy on home loans for EWS, LIG, and MIG families to help them buy or build their first home.",
    whatIsIt: "PMAY-Urban provides credit-linked subsidy on home loans under the Credit Linked Subsidy Scheme (CLSS). Eligible families get a subsidy of up to ₹2.67 lakh on interest, reducing EMIs significantly. The scheme targets families who do not own a pucca house.",
    benefits: ["Interest subsidy up to ₹2.67 lakh (EWS/LIG)", "Subsidy up to ₹2.35 lakh (MIG-I)", "Subsidy up to ₹2.30 lakh (MIG-II)", "Reduced EMIs for 20-year loan tenure", "No minimum loan amount requirement"],
    documents: ["Aadhaar card", "Income proof / salary slips", "Property documents", "Bank account details", "Self-declaration that you don't own a pucca house"],
    howToApply: ["Visit pmaymis.gov.in", "Select 'Citizen Assessment'", "Choose your category (EWS/LIG/MIG)", "Fill the online form with Aadhaar-verified details", "Submit to your bank or housing finance company", "Bank processes the subsidy directly"],
    eligibilityRules: {
      logic: "AND",
      conditions: [
        { field: "income", operator: "lte", value: 800000, label: "Annual income up to ₹8 lakh" },
        { field: "age", operator: "gte", value: 18, label: "Age 18 or above" },
      ],
    },
    eligibilityText: "Families with annual income up to ₹8 lakh who do not own a pucca house",
    officialLink: "https://pmaymis.gov.in",
    applyLink: "https://pmaymis.gov.in/Open/Citizens_Assessment.aspx",
  },
  {
    slug: "pm-ujjwala-yojana",
    name: "PM Ujjwala Yojana",
    nameHindi: "प्रधानमंत्री उज्ज्वला योजना",
    tagline: "Free LPG connection for women from BPL families",
    category: "women",
    ministry: "Ministry of Petroleum & Natural Gas",
    icon: "🔥",
    bgColor: "#FEE2E2",
    shortDescription: "Free LPG gas connection to women from Below Poverty Line (BPL) households, ending dependence on wood/coal cooking.",
    whatIsIt: "PMUY provides a free LPG connection (cylinder, regulator, pipe) to women from poor households. It aims to replace traditional chulhas fuelled by wood or coal, reducing health hazards from indoor pollution. The connection is given in the woman's name.",
    benefits: ["Free LPG connection (no deposit)", "Free first refill cylinder", "Free pressure regulator and pipe", "Connection in woman's name", "Optional 0% interest EMI for stove"],
    documents: ["Aadhaar card", "BPL ration card or income certificate", "Bank account (in woman's name)", "Passport size photo"],
    howToApply: ["Visit your nearest LPG distributor (HP, Bharat, or Indane Gas)", "Ask for PMUY application form", "Fill form with Aadhaar and bank details", "Submit with documents", "Connection installed within 3 days of verification"],
    eligibilityRules: {
      logic: "AND",
      conditions: [
        { field: "income", operator: "lte", value: 100000, label: "Annual income up to ₹1 lakh (BPL)" },
        { field: "age", operator: "gte", value: 18, label: "Age 18 or above" },
        { field: "gender", operator: "eq", value: "Female", label: "Must be female applicant" },
      ],
    },
    eligibilityText: "Women aged 18+ from BPL families (income below ₹1 lakh/year)",
    officialLink: "https://www.pmuy.gov.in",
    applyLink: "https://www.pmuy.gov.in/ujjwala2.html",
  },
  {
    slug: "atal-pension-yojana",
    name: "Atal Pension Yojana",
    nameHindi: "अटल पेंशन योजना",
    tagline: "Guaranteed pension of ₹1,000–₹5,000/month after 60",
    category: "pension",
    ministry: "Ministry of Finance — PFRDA",
    icon: "🧓",
    bgColor: "#F3F4F6",
    shortDescription: "Government-backed pension scheme for unorganised sector workers guaranteeing ₹1,000–₹5,000/month pension after age 60.",
    whatIsIt: "APY is a pension scheme for workers in the unorganised sector. You contribute a fixed amount every month based on your age and chosen pension amount. After turning 60, you get a guaranteed monthly pension. The government also contributes 50% of your contribution (up to ₹1,000/year) for 5 years.",
    benefits: ["Guaranteed pension ₹1,000 to ₹5,000/month after 60", "Government co-contribution of 50% (up to ₹1,000/year)", "Spouse continues pension after subscriber's death", "Nominee receives full corpus on death", "Auto-debit from savings account"],
    documents: ["Aadhaar card", "Savings bank account", "Mobile number linked to account"],
    howToApply: ["Visit your bank or post office", "Ask for APY enrollment form", "Fill in pension amount and nominee details", "Set up auto-debit from savings account", "First contribution deducted in same month"],
    eligibilityRules: {
      logic: "AND",
      conditions: [
        { field: "age", operator: "range", value: [18, 40], label: "Age between 18 and 40" },
        { field: "occupation", operator: "in", value: ["Daily Wage / Labour", "Farmer", "Street Vendor", "Homemaker", "Self-employed / Small Business"], label: "Unorganised sector worker" },
      ],
    },
    eligibilityText: "Unorganised sector workers aged 18–40 years",
    officialLink: "https://www.npscra.nsdl.co.in/scheme-details.php",
    applyLink: "https://enps.nsdl.com/eNPS/APYSchemeDetails.html",
  },
  {
    slug: "pm-mudra-yojana",
    name: "PM Mudra Yojana",
    nameHindi: "प्रधानमंत्री मुद्रा योजना",
    tagline: "Business loans from ₹50,000 to ₹10 lakh — no collateral",
    category: "business",
    ministry: "Ministry of Finance — MUDRA",
    icon: "💼",
    bgColor: "#DBEAFE",
    shortDescription: "Collateral-free loans for non-farm micro and small businesses under three categories: Shishu, Kishore, and Tarun.",
    whatIsIt: "MUDRA provides loans to small businesses, vendors, artisans, and self-employed individuals through banks, MFIs, and NBFCs. Three tiers: Shishu (up to ₹50,000), Kishore (₹50,000–₹5 lakh), Tarun (₹5–₹10 lakh). No collateral required for Shishu and Kishore loans.",
    benefits: ["Shishu: loans up to ₹50,000 at low interest", "Kishore: ₹50,000 to ₹5 lakh", "Tarun: ₹5 lakh to ₹10 lakh", "No collateral for Shishu & Kishore", "Mudra Card for working capital needs"],
    documents: ["Aadhaar card", "PAN card", "Business address proof", "Business plan or last 2 years' accounts", "Photos", "Bank statements (6 months)"],
    howToApply: ["Visit your nearest bank, NBFC, or MFI", "Ask for Mudra loan form", "Choose tier: Shishu, Kishore, or Tarun", "Submit business details and documents", "Bank appraises application (7-14 days)", "Loan disbursed with Mudra Card"],
    eligibilityRules: {
      logic: "AND",
      conditions: [
        { field: "income", operator: "lte", value: 800000, label: "Annual income up to ₹8 lakh" },
        { field: "occupation", operator: "in", value: ["Self-employed / Small Business", "Street Vendor", "Farmer"], label: "Self-employed, vendor, or small business" },
        { field: "age", operator: "gte", value: 18, label: "Age 18 or above" },
      ],
    },
    eligibilityText: "Self-employed, vendors, and small business owners with annual income below ₹8 lakh",
    officialLink: "https://www.mudra.org.in",
    applyLink: "https://udyamimitra.in",
  },
  {
    slug: "post-matric-scholarship-sc-st",
    name: "Post Matric Scholarship for SC/ST",
    nameHindi: "अनुसूचित जाति/जनजाति के लिए पोस्ट मैट्रिक छात्रवृत्ति",
    tagline: "Full tuition + allowance for SC/ST students after Class 10",
    category: "student",
    ministry: "Ministry of Social Justice & Empowerment",
    icon: "🎓",
    bgColor: "#FEF9C3",
    shortDescription: "Full fee reimbursement plus monthly maintenance allowance for SC/ST students enrolled in post-matric courses.",
    whatIsIt: "This scholarship reimburses full tuition fees and provides a monthly maintenance allowance for SC and ST students studying in Class 11, 12, or any college/university course. It covers all government and private recognised institutions.",
    benefits: ["Full tuition fee reimbursement", "Maintenance allowance ₹570–₹1,200/month (hostellers get more)", "Book allowance", "Study tour allowance", "Thesis/dissertation allowance for research students"],
    documents: ["Caste certificate (SC/ST)", "Income certificate (family income below ₹2.5 lakh)", "Aadhaar card", "Institution enrollment certificate", "Previous year marksheet", "Bank account in student's name"],
    howToApply: ["Register on scholarships.gov.in", "Select 'Post Matric Scholarship for SC Students' or ST variant", "Fill academic and income details", "Upload caste and income certificates", "Submit before state deadline (typically October)", "Scholarship credited to bank account"],
    eligibilityRules: {
      logic: "AND",
      conditions: [
        { field: "category", operator: "in", value: ["SC", "ST"], label: "Must be SC or ST category" },
        { field: "occupation", operator: "eq", value: "Student", label: "Must be a student" },
        { field: "income", operator: "lte", value: 250000, label: "Family income up to ₹2.5 lakh" },
      ],
    },
    eligibilityText: "SC/ST students enrolled in post-matric education with family income below ₹2.5 lakh",
    officialLink: "https://scholarships.gov.in",
    applyLink: "https://scholarships.gov.in/fresh/loginPage",
  },
  {
    slug: "pm-svanidhi",
    name: "PM SVANidhi — Street Vendor Loan",
    nameHindi: "पीएम स्वनिधि",
    tagline: "Micro loans ₹10,000–₹50,000 for street vendors",
    category: "vendor",
    ministry: "Ministry of Housing & Urban Affairs",
    icon: "🛒",
    bgColor: "#FFEDD5",
    shortDescription: "Collateral-free working capital loans for street vendors with interest subsidy and credit score benefits.",
    whatIsIt: "PM SVANidhi rehabilitates street vendors who lost livelihoods during COVID. First loan: ₹10,000. After timely repayment, eligible for ₹20,000, then ₹50,000. 7% interest subsidy paid into bank account. Digital payments encouraged with cashback incentives.",
    benefits: ["First loan: ₹10,000 (no collateral)", "Second loan: ₹20,000 on timely repayment", "Third loan: ₹50,000", "7% interest subsidy credited quarterly", "Credit score building", "₹100/month cashback on digital payments"],
    documents: ["Aadhaar card", "Certificate of Vending (CoV) or Letter of Recommendation from ULB", "Bank account or Jan Dhan account", "Mobile number"],
    howToApply: ["Download PM SVANidhi app or visit pmsvanidhi.mohua.gov.in", "Apply for Letter of Recommendation from your Town Vending Committee", "Submit loan application at any bank, MFI, or SHG lender", "Loan disbursed within 30 days", "Repay on time to upgrade loan amount"],
    eligibilityRules: {
      logic: "AND",
      conditions: [
        { field: "occupation", operator: "eq", value: "Street Vendor", label: "Must be a street vendor" },
        { field: "age", operator: "gte", value: 18, label: "Age 18 or above" },
      ],
    },
    eligibilityText: "Street vendors aged 18+ operating before March 24, 2020",
    officialLink: "https://pmsvanidhi.mohua.gov.in",
    applyLink: "https://pmsvanidhi.mohua.gov.in/Home/Applyloan",
  },
  {
    slug: "sukanya-samriddhi-yojana",
    name: "Sukanya Samriddhi Yojana",
    nameHindi: "सुकन्या समृद्धि योजना",
    tagline: "8.2% savings account for daughters — best rate in India",
    category: "women",
    ministry: "Ministry of Finance",
    icon: "👧",
    bgColor: "#FCE7F3",
    shortDescription: "High-interest savings scheme (8.2% p.a.) for parents investing for their daughter's education and marriage expenses.",
    whatIsIt: "SSY is a small savings scheme where parents/guardians open an account for a girl child below age 10. Current interest rate is 8.2% per annum (tax-free). Minimum deposit ₹250/year. Matures after 21 years or when girl turns 18 (whichever is earlier). Partial withdrawal allowed for education after age 18.",
    benefits: ["Interest rate: 8.2% per annum (quarterly compounded)", "Tax-free returns under Section 80C", "Minimum deposit: ₹250/year", "Maximum: ₹1.5 lakh/year", "Partial withdrawal (50%) after daughter turns 18 for education"],
    documents: ["Girl child's birth certificate", "Parent/guardian Aadhaar card", "Parent/guardian PAN card", "Address proof"],
    howToApply: ["Visit any post office or authorised bank (SBI, PNB, etc.)", "Fill SSY account opening form", "Deposit minimum ₹250 to open account", "Passbook issued immediately", "Deposit annually — minimum ₹250, maximum ₹1.5 lakh"],
    eligibilityRules: {
      logic: "AND",
      conditions: [
        { field: "age", operator: "lte", value: 50, label: "Parent/guardian below 50 years" },
      ],
    },
    eligibilityText: "Parents or guardians of a girl child below age 10",
    officialLink: "https://www.indiapost.gov.in/Financial/Pages/Content/sukanya-samriddhi.aspx",
    applyLink: "https://www.indiapost.gov.in",
  },
  {
    slug: "startup-india-seed-fund",
    name: "Startup India Seed Fund Scheme",
    nameHindi: "स्टार्टअप इंडिया सीड फंड",
    tagline: "Up to ₹50 lakh funding + 3-year tax holiday for startups",
    category: "business",
    ministry: "Department for Promotion of Industry and Internal Trade (DPIIT)",
    icon: "🚀",
    bgColor: "#E0F2FE",
    shortDescription: "Financial assistance to early-stage startups for proof of concept, prototype development, product trials, and market entry.",
    whatIsIt: "SISFS provides up to ₹50 lakh in seed funding to DPIIT-recognized startups through incubators. Additionally, registered startups get a 3-year income tax holiday, capital gains exemption, and angel tax exemption. Apply through DPIIT recognition first.",
    benefits: ["Up to ₹50 lakh seed funding via incubators", "3 consecutive years income tax exemption (Section 80-IAC)", "Capital gains tax exemption (Section 54EE)", "Angel tax exemption", "Fast-track patent filing with 80% fee rebate"],
    documents: ["Company registration / incorporation certificate", "DPIIT startup recognition number", "Business plan / pitch deck", "Financial projections", "PAN and GST registration", "Bank account details"],
    howToApply: ["Register your startup at startupindia.gov.in", "Get DPIIT recognition (takes 2-3 working days)", "Apply for Seed Fund through registered incubators on the portal", "Incubator evaluates your application (30-60 days)", "Funding disbursed in milestones"],
    eligibilityRules: {
      logic: "AND",
      conditions: [
        { field: "occupation", operator: "in", value: ["Self-employed / Small Business", "Salaried (Government)", "Salaried (Private)"], label: "Business owner or salaried professional" },
        { field: "age", operator: "range", value: [18, 50], label: "Age between 18 and 50" },
        { field: "income", operator: "lte", value: 800000, label: "Income up to ₹8 lakh (early stage)" },
      ],
    },
    eligibilityText: "Early-stage startup founders with DPIIT-recognized company, aged 18–50",
    officialLink: "https://www.startupindia.gov.in",
    applyLink: "https://www.startupindia.gov.in/content/sih/en/seed-fund-scheme.html",
  },
  // ─── State-specific schemes ───────────────────────────────────────────────
  {
    slug: "maha-dbte-scholarship",
    name: "Maharashtra DBT Scholarship (EBC)",
    nameHindi: "महाराष्ट्र ईबीसी छात्रवृत्ति",
    tagline: "Tuition fee waiver for economically backward students in Maharashtra",
    category: "student",
    ministry: "Social Justice & Special Assistance Dept — Maharashtra",
    icon: "📚",
    bgColor: "#FEF3C7",
    shortDescription: "Full tuition fee reimbursement for students from economically backward classes in Maharashtra's government and aided colleges.",
    whatIsIt: "The Maharashtra EBC scholarship covers full tuition fees for students from families with annual income below ₹8 lakh enrolled in government and government-aided colleges. Disbursed directly to the college under the Direct Benefit Transfer system.",
    benefits: ["Full tuition fee waiver", "Applicable to graduation and post-graduation", "Covers government and aided institutions", "Direct payment to institution — no hassle"],
    documents: ["Income certificate (below ₹8 lakh)", "Maharashtra domicile certificate (15 years)", "Aadhaar card", "Enrollment certificate from college", "Previous year marksheet", "Bank account"],
    howToApply: ["Register on mahadbt.maharashtra.gov.in", "Select EBC scholarship scheme", "Upload income and domicile certificates", "College verifies and approves", "Fee credited directly to college"],
    eligibilityRules: {
      logic: "AND",
      conditions: [
        { field: "occupation", operator: "eq", value: "Student", label: "Must be a student" },
        { field: "state", operator: "eq", value: "Maharashtra", label: "Must be Maharashtra resident" },
        { field: "income", operator: "lte", value: 800000, label: "Family income up to ₹8 lakh" },
      ],
    },
    eligibilityText: "Students enrolled in Maharashtra colleges with family income below ₹8 lakh",
    officialLink: "https://mahadbt.maharashtra.gov.in",
    applyLink: "https://mahadbt.maharashtra.gov.in/SchemeData/SchemeData",
  },
  {
    slug: "up-kisan-karj-rahat",
    name: "UP Kisan Karj Rahat Yojana",
    nameHindi: "उत्तर प्रदेश किसान कर्ज राहत योजना",
    tagline: "Loan waiver up to ₹1 lakh for small farmers in Uttar Pradesh",
    category: "farmer",
    ministry: "Agriculture Department — Uttar Pradesh",
    icon: "🌾",
    bgColor: "#DCFCE7",
    shortDescription: "One-time farm loan waiver of up to ₹1 lakh for small and marginal farmers with outstanding crop loans in UP.",
    whatIsIt: "The UP Kisan Karj Rahat scheme waives outstanding crop loans up to ₹1 lakh taken from cooperative banks, regional rural banks, or nationalised banks for small and marginal farmers. Farmers must own less than 2 hectares of agricultural land.",
    benefits: ["Loan waiver up to ₹1 lakh", "Applicable to cooperative, RRB, and nationalised bank loans", "Covers crop loans (KCC) only", "Certificate of debt relief issued"],
    documents: ["Aadhaar card linked to bank account", "Kisan Credit Card (KCC) or loan account details", "Land records (below 2 hectares)", "Bank passbook"],
    howToApply: ["Visit upkisankarjrahat.upsdc.gov.in", "Check your eligibility using Aadhaar or account number", "Eligible farmers automatically notified", "Waiver credited directly to loan account"],
    eligibilityRules: {
      logic: "AND",
      conditions: [
        { field: "occupation", operator: "eq", value: "Farmer", label: "Must be a farmer" },
        { field: "state", operator: "eq", value: "Uttar Pradesh", label: "Must be UP resident" },
        { field: "income", operator: "lte", value: 200000, label: "Annual income up to ₹2 lakh" },
      ],
    },
    eligibilityText: "Small and marginal UP farmers with outstanding crop loans and land below 2 hectares",
    officialLink: "https://upkisankarjrahat.upsdc.gov.in",
    applyLink: "https://upkisankarjrahat.upsdc.gov.in",
  },
  {
    slug: "rajasthan-free-mobile-yojana",
    name: "Rajasthan Free Mobile Yojana",
    nameHindi: "राजस्थान मुफ्त मोबाइल योजना",
    tagline: "Free smartphone with 3 years of data for women in Rajasthan",
    category: "women",
    ministry: "Department of Information Technology — Rajasthan",
    icon: "📱",
    bgColor: "#FCE7F3",
    shortDescription: "Free smartphone with 3-year internet and calling plan for women heads of households under Chiranjeevi families in Rajasthan.",
    whatIsIt: "Under the Indira Gandhi Free Smartphone Yojana, Rajasthan provides free smartphones to women who are heads of households enrolled in the Chiranjeevi health scheme. The package includes the phone plus 3 years of free data (unlimited calls, 2 GB/day data).",
    benefits: ["Free smartphone (worth ₹6,800+)", "3 years of free SIM with data plan", "Unlimited calling", "2 GB data per day for 3 years", "Provided via camp-based distribution"],
    documents: ["Chiranjeevi card or Jan Aadhaar card", "Aadhaar card of female head of household", "Rajasthan domicile proof"],
    howToApply: ["Check camp schedule at igsy.rajasthan.gov.in", "Visit your nearest distribution camp with documents", "Biometric verification done at camp", "Phone and SIM issued on the spot"],
    eligibilityRules: {
      logic: "AND",
      conditions: [
        { field: "state", operator: "eq", value: "Rajasthan", label: "Must be Rajasthan resident" },
        { field: "gender", operator: "eq", value: "Female", label: "Female head of household" },
        { field: "age", operator: "gte", value: 18, label: "Age 18 or above" },
      ],
    },
    eligibilityText: "Female heads of households enrolled in Chiranjeevi / Jan Aadhaar scheme in Rajasthan",
    officialLink: "https://igsy.rajasthan.gov.in",
    applyLink: "https://igsy.rajasthan.gov.in",
  },
  {
    slug: "karnataka-rajiv-gandhi-health-scheme",
    name: "Karnataka Arogya Karnataka Scheme",
    nameHindi: "कर्नाटक आरोग्य कर्नाटक",
    tagline: "Free healthcare up to ₹5 lakh/year for Karnataka families",
    category: "health",
    ministry: "Health & Family Welfare — Karnataka",
    icon: "❤️",
    bgColor: "#FEE2E2",
    shortDescription: "Universal health coverage providing cashless treatment up to ₹5 lakh/year at government and empanelled private hospitals in Karnataka.",
    whatIsIt: "Arogya Karnataka provides cashless medical treatment to all Karnataka residents. APL families get coverage up to ₹1.5 lakh, BPL families up to ₹5 lakh per year. Covers 1,600+ procedures across all specialties. Treatment at government hospitals is free; network private hospitals are empanelled.",
    benefits: ["APL: up to ₹1.5 lakh/year coverage", "BPL/Antodaya: up to ₹5 lakh/year coverage", "1,600+ surgical procedures and treatments covered", "Cashless treatment at 250+ network hospitals", "Pre-existing conditions covered from day 1"],
    documents: ["Karnataka ration card or domicile proof", "Aadhaar card", "Income certificate (for BPL tier)", "Any government photo ID"],
    howToApply: ["Visit your nearest government hospital or PHC", "Request Arogya Karnataka enrollment", "Biometric registration done at hospital", "Beneficiary card issued within minutes", "Use card for cashless treatment immediately"],
    eligibilityRules: {
      logic: "AND",
      conditions: [
        { field: "state", operator: "eq", value: "Karnataka", label: "Must be Karnataka resident" },
        { field: "age", operator: "gte", value: 0, label: "All ages covered" },
      ],
    },
    eligibilityText: "All Karnataka residents — BPL families get higher coverage up to ₹5 lakh",
    officialLink: "https://arogyakarnataka.kar.nic.in",
    applyLink: "https://arogyakarnataka.kar.nic.in",
  },

  // ─── 10 NEW SCHEMES ───────────────────────────────────────────────────────

  {
    slug: "ayushman-bharat-pmjay",
    name: "Ayushman Bharat — PM Jan Arogya Yojana",
    nameHindi: "आयुष्मान भारत — प्रधानमंत्री जन आरोग्य योजना",
    tagline: "Free hospitalisation up to ₹5 lakh/year for poor families",
    category: "health",
    ministry: "Ministry of Health & Family Welfare",
    icon: "🏥",
    bgColor: "#FEE2E2",
    shortDescription: "Health cover of ₹5 lakh per family per year for secondary and tertiary hospitalisation at any empanelled hospital across India — completely cashless.",
    whatIsIt: "PM-JAY is the world's largest government-funded health insurance scheme covering over 10 crore poor and vulnerable families. Beneficiaries get cashless treatment at any of 25,000+ empanelled public or private hospitals for 1,929 medical procedures including surgeries, ICU, dialysis, cancer treatment, and more.",
    benefits: [
      "₹5 lakh health cover per family per year",
      "Cashless and paperless treatment at 25,000+ hospitals",
      "Covers pre and post-hospitalisation expenses",
      "No premium payment by beneficiary",
      "All pre-existing conditions covered from day one",
      "1,929 surgical and medical procedures covered",
    ],
    documents: [
      "Aadhaar card",
      "Ration card or SECC 2011 enrollment",
      "Ayushman card (made free at hospital or CSC)",
    ],
    howToApply: [
      "Check eligibility at pmjay.gov.in or call 14555",
      "Visit nearest Common Service Centre (CSC) or empanelled hospital",
      "Get your free Ayushman card made",
      "Use the card at any empanelled hospital for cashless treatment",
    ],
    eligibilityRules: {
      logic: "AND",
      conditions: [
        { field: "income", operator: "lte", value: 100000, label: "BPL or low-income family" },
        { field: "age", operator: "gte", value: 0, label: "All ages covered" },
      ],
    },
    eligibilityText: "Bottom 40% of Indian population based on SECC 2011 data — check eligibility at pmjay.gov.in",
    officialLink: "https://pmjay.gov.in",
    applyLink: "https://beneficiary.nha.gov.in",
  },

  {
    slug: "pm-suraksha-bima-yojana",
    name: "PM Suraksha Bima Yojana",
    nameHindi: "प्रधानमंत्री सुरक्षा बीमा योजना",
    tagline: "₹2 lakh accident insurance for just ₹20 per year",
    category: "general",
    ministry: "Ministry of Finance",
    icon: "🛡️",
    bgColor: "#DBEAFE",
    shortDescription: "Accidental death and disability insurance of ₹2 lakh for just ₹20 per year — the most affordable insurance scheme in India, open to all bank account holders.",
    whatIsIt: "PMSBY provides ₹2 lakh insurance cover on accidental death or total permanent disability, and ₹1 lakh for partial permanent disability. The annual premium of just ₹20 is auto-debited from your savings account every year. No medical tests needed. Available to all savings bank account holders aged 18–70.",
    benefits: [
      "₹2 lakh payout on accidental death",
      "₹2 lakh on total permanent disability",
      "₹1 lakh on partial permanent disability",
      "Premium only ₹20 per year",
      "Auto-renews every year from bank account",
    ],
    documents: [
      "Savings bank account",
      "Aadhaar card",
      "Mobile number linked to bank account",
    ],
    howToApply: [
      "Visit your bank branch, net banking, or mobile banking app",
      "Ask to enroll in PM Suraksha Bima Yojana",
      "Give consent for ₹20 annual auto-debit",
      "Insurance certificate sent to registered mobile number",
    ],
    eligibilityRules: {
      logic: "AND",
      conditions: [
        { field: "age", operator: "range", value: [18, 70], label: "Age between 18 and 70" },
      ],
    },
    eligibilityText: "All savings bank account holders aged 18–70 years",
    officialLink: "https://www.jansuraksha.gov.in/PMSBY.aspx",
    applyLink: "https://www.jansuraksha.gov.in/PMSBY.aspx",
  },

  {
    slug: "pm-jeevan-jyoti-bima-yojana",
    name: "PM Jeevan Jyoti Bima Yojana",
    nameHindi: "प्रधानमंत्री जीवन ज्योति बीमा योजना",
    tagline: "₹2 lakh life insurance for just ₹436 per year — no medical test",
    category: "general",
    ministry: "Ministry of Finance",
    icon: "💙",
    bgColor: "#EFF6FF",
    shortDescription: "Pure term life insurance of ₹2 lakh for death from any cause — accident or natural — at just ₹436 per year. No medical examination required.",
    whatIsIt: "PMJJBY provides ₹2 lakh life insurance on death due to any reason — accident or illness. Premium is ₹436/year, auto-debited from your savings bank account. No medical tests required. Available to savings bank account holders aged 18–50. Cover renews automatically every year.",
    benefits: [
      "₹2 lakh life cover on death from any cause",
      "No medical tests required",
      "Premium only ₹436 per year",
      "Auto-renews every year",
      "Nominee receives full amount within 30 days of claim",
    ],
    documents: [
      "Savings bank account",
      "Aadhaar card",
      "Nominee details (family member name and relation)",
    ],
    howToApply: [
      "Visit your bank branch, net banking, or mobile banking app",
      "Enroll in PM Jeevan Jyoti Bima Yojana",
      "Provide nominee details",
      "Give consent for ₹436 annual auto-debit",
      "Policy document sent to registered mobile or email",
    ],
    eligibilityRules: {
      logic: "AND",
      conditions: [
        { field: "age", operator: "range", value: [18, 50], label: "Age between 18 and 50" },
      ],
    },
    eligibilityText: "All savings bank account holders aged 18–50 years",
    officialLink: "https://www.jansuraksha.gov.in/PMJJBY.aspx",
    applyLink: "https://www.jansuraksha.gov.in/PMJJBY.aspx",
  },

  {
    slug: "pm-matru-vandana-yojana",
    name: "Pradhan Mantri Matru Vandana Yojana",
    nameHindi: "प्रधानमंत्री मातृ वंदना योजना",
    tagline: "₹5,000 cash benefit for pregnant women and new mothers",
    category: "women",
    ministry: "Ministry of Women & Child Development",
    icon: "🤱",
    bgColor: "#FCE7F3",
    shortDescription: "Cash incentive of ₹5,000 in instalments to pregnant women and nursing mothers for their first live birth — to promote safe delivery and good nutrition.",
    whatIsIt: "PMMVY provides ₹5,000 directly to pregnant and lactating women for their first living child in three instalments. It compensates for wage loss during pregnancy and encourages safe motherhood practices. An additional ₹1,000 is given under Janani Suraksha Yojana for institutional delivery, making total benefit up to ₹6,000.",
    benefits: [
      "₹3,000 first instalment on early pregnancy registration",
      "₹2,000 second instalment after 6 months with ANC checkup",
      "Additional ₹1,000 for institutional delivery",
      "Total benefit up to ₹6,000",
      "Direct bank transfer to woman's account",
    ],
    documents: [
      "Aadhaar card",
      "Bank account in woman's name",
      "MCP (Mother Child Protection) card",
      "Marriage certificate or self-declaration",
    ],
    howToApply: [
      "Register at nearest Anganwadi centre or health facility",
      "Fill PMMVY Form 1A within first trimester",
      "Submit Form 1B after 6 months with ANC record",
      "Submit Form 1C after baby's birth",
      "Money transferred directly to bank account",
    ],
    eligibilityRules: {
      logic: "AND",
      conditions: [
        { field: "gender", operator: "eq", value: "Female", label: "Must be female" },
        { field: "age", operator: "gte", value: 19, label: "Age 19 or above" },
      ],
    },
    eligibilityText: "Pregnant women and nursing mothers aged 19+ for their first live birth",
    officialLink: "https://pmmvy.wcd.gov.in",
    applyLink: "https://pmmvy.wcd.gov.in",
  },

  {
    slug: "pm-fasal-bima-yojana",
    name: "Pradhan Mantri Fasal Bima Yojana",
    nameHindi: "प्रधानमंत्री फसल बीमा योजना",
    tagline: "Crop insurance at just 2% premium — protect your harvest",
    category: "farmer",
    ministry: "Ministry of Agriculture & Farmers Welfare",
    icon: "🌱",
    bgColor: "#ECFDF5",
    shortDescription: "Crop insurance protecting farmers from financial loss due to floods, drought, hailstorm, pest attack — government pays 98% of the premium.",
    whatIsIt: "PMFBY provides comprehensive crop insurance at just 2% premium for Kharif crops, 1.5% for Rabi, and 5% for horticulture crops. The government pays the remaining premium. If crops fail due to natural disasters, farmers receive full compensation directly in their bank account within 2 months.",
    benefits: [
      "Farmer pays only 2% premium for Kharif crops",
      "1.5% premium for Rabi crops",
      "Full compensation for crop loss due to natural disasters",
      "Coverage from pre-sowing to post-harvest",
      "SMS alerts for claim status",
      "Covers localised risks like hailstorm and landslide",
    ],
    documents: [
      "Aadhaar card",
      "Land records (Khasra/Khatauni)",
      "Bank passbook",
      "Sowing certificate from Patwari",
      "Mobile number",
    ],
    howToApply: [
      "Visit nearest bank, PACS, or CSC before cutoff (July 31 for Kharif)",
      "Fill PMFBY enrollment form with crop and land details",
      "Pay 2% premium — government pays the rest",
      "Get policy number via SMS",
      "Report any crop loss to bank or insurer within 72 hours of damage",
    ],
    eligibilityRules: {
      logic: "AND",
      conditions: [
        { field: "occupation", operator: "eq", value: "Farmer", label: "Must be a farmer" },
        { field: "age", operator: "gte", value: 18, label: "Age 18 or above" },
      ],
    },
    eligibilityText: "All farmers — loanee and non-loanee — growing notified crops in notified areas",
    officialLink: "https://pmfby.gov.in",
    applyLink: "https://pmfby.gov.in",
  },

  {
    slug: "kisan-credit-card",
    name: "Kisan Credit Card (KCC)",
    nameHindi: "किसान क्रेडिट कार्ड",
    tagline: "Crop loan up to ₹3 lakh at 4% effective interest rate",
    category: "farmer",
    ministry: "Ministry of Agriculture & Farmers Welfare",
    icon: "💳",
    bgColor: "#FEF9C3",
    shortDescription: "Flexible credit card for farmers giving access to short-term crop loans at just 4% effective interest after government subvention — no collateral up to ₹1.6 lakh.",
    whatIsIt: "KCC gives farmers easy revolving credit to buy seeds, fertilizers, pesticides, and meet labour costs. Interest rate is 7% but government gives 3% subvention for timely repayment, making effective rate just 4%. Credit limit is decided based on your land area and crops grown. Includes personal accident insurance.",
    benefits: [
      "Crop loan up to ₹3 lakh at 4% effective interest rate",
      "No collateral required up to ₹1.6 lakh",
      "Flexible — withdraw and repay as needed",
      "Covers seeds, fertilizers, pesticides, and labour costs",
      "Post-harvest and allied activity expenses covered",
      "Personal accident insurance included",
    ],
    documents: [
      "Aadhaar card",
      "Land records (must be in applicant's name)",
      "Passport size photo",
      "Two references",
    ],
    howToApply: [
      "Visit nearest bank branch (SBI, PNB, cooperative bank, etc.)",
      "Ask for Kisan Credit Card application form",
      "Submit land records and income details",
      "Bank assesses credit limit based on land holding",
      "KCC issued within 15 working days",
    ],
    eligibilityRules: {
      logic: "AND",
      conditions: [
        { field: "occupation", operator: "eq", value: "Farmer", label: "Must be a farmer" },
        { field: "age", operator: "range", value: [18, 75], label: "Age between 18 and 75" },
      ],
    },
    eligibilityText: "All farmers — owner cultivators, tenant farmers, sharecroppers, and SHG members",
    officialLink: "https://www.nabard.org/content1.aspx?id=572",
    applyLink: "https://www.sbi.co.in/web/agri-rural/agriculture-banking/crop-loan/kisan-credit-card",
  },

  {
    slug: "e-shram-portal",
    name: "e-Shram Portal — Unorganised Workers Registration",
    nameHindi: "ई-श्रम पोर्टल",
    tagline: "Free ₹2 lakh accident insurance — register in 2 minutes",
    category: "labour",
    ministry: "Ministry of Labour & Employment",
    icon: "🔨",
    bgColor: "#FEF9C3",
    shortDescription: "National registration for unorganised workers — get a free e-Shram card with ₹2 lakh PMSBY accident insurance and first priority for all future government schemes.",
    whatIsIt: "e-Shram is a national database for all unorganised workers — construction labourers, domestic workers, gig workers, street vendors, agricultural workers, fishermen, and more. Registered workers get a 12-digit UAN (Universal Account Number), ₹2 lakh accident insurance under PMSBY, and first access to all future government welfare schemes.",
    benefits: [
      "Free ₹2 lakh accident insurance under PMSBY",
      "Unique e-Shram card with 12-digit UAN number",
      "First priority access to future welfare schemes",
      "Benefits portable — follow you across states",
      "Free to register — takes just 2 minutes",
    ],
    documents: [
      "Aadhaar card linked to mobile number",
      "Bank account details",
      "IFSC code of your bank branch",
    ],
    howToApply: [
      "Visit eshram.gov.in or nearest CSC centre",
      "Enter Aadhaar number and mobile OTP",
      "Fill in occupation, income, and bank details",
      "Download your e-Shram card — registration complete in 2 minutes",
    ],
    eligibilityRules: {
      logic: "AND",
      conditions: [
        { field: "occupation", operator: "in", value: ["Daily Wage / Labour", "Street Vendor", "Farmer", "Homemaker", "Unemployed", "Self-employed / Small Business"], label: "Unorganised sector worker" },
        { field: "age", operator: "range", value: [16, 59], label: "Age between 16 and 59" },
        { field: "income", operator: "lte", value: 300000, label: "Not in income tax bracket" },
      ],
    },
    eligibilityText: "All unorganised sector workers aged 16–59 not covered under EPFO, ESIC, or NPS",
    officialLink: "https://eshram.gov.in",
    applyLink: "https://register.eshram.gov.in",
  },

  {
    slug: "stand-up-india",
    name: "Stand-Up India Scheme",
    nameHindi: "स्टैंड-अप इंडिया",
    tagline: "₹10 lakh to ₹1 crore business loan for SC/ST and women entrepreneurs",
    category: "business",
    ministry: "Ministry of Finance — SIDBI",
    icon: "📈",
    bgColor: "#F0F9FF",
    shortDescription: "Bank loans from ₹10 lakh to ₹1 crore to SC/ST and women entrepreneurs for setting up new manufacturing, service, or trading businesses — no collateral required.",
    whatIsIt: "Stand-Up India ensures at least one SC/ST borrower and one woman borrower per bank branch gets a loan of ₹10 lakh to ₹1 crore for setting up a greenfield enterprise. The government provides 75% credit guarantee to banks, making loans easier to get. Covers manufacturing, services, and trading sectors.",
    benefits: [
      "Loans from ₹10 lakh to ₹1 crore",
      "75% government credit guarantee — no collateral needed",
      "7-year repayment tenure",
      "Covers up to 75% of project cost",
      "Free mentorship and handholding support",
      "Subsidised interest rates",
    ],
    documents: [
      "Aadhaar card and PAN card",
      "Caste certificate (for SC/ST applicants)",
      "Detailed business plan and project report",
      "Last 2 years income tax returns (if applicable)",
      "Bank statements for 6 months",
    ],
    howToApply: [
      "Register at standupmitra.in",
      "Browse partner banks and lenders listed on the portal",
      "Submit loan application online or at bank branch",
      "Bank appraises your application within 30–60 days",
      "Loan sanctioned and disbursed in stages",
    ],
    eligibilityRules: {
      logic: "OR",
      conditions: [
        { field: "category", operator: "in", value: ["SC", "ST"], label: "SC or ST category" },
        { field: "gender", operator: "eq", value: "Female", label: "Female entrepreneur" },
      ],
    },
    eligibilityText: "SC/ST individuals OR women entrepreneurs setting up a greenfield business for the first time",
    officialLink: "https://www.standupmitra.in",
    applyLink: "https://www.standupmitra.in/Home/SuiLoan",
  },

  {
    slug: "pmegp-scheme",
    name: "PM Employment Generation Programme (PMEGP)",
    nameHindi: "प्रधानमंत्री रोजगार सृजन कार्यक्रम",
    tagline: "25–35% government subsidy on business loans up to ₹50 lakh",
    category: "business",
    ministry: "Ministry of MSME — KVIC",
    icon: "🏭",
    bgColor: "#FFF7ED",
    shortDescription: "Government pays 25–35% of your business project cost as a non-refundable subsidy for setting up a new manufacturing or service micro enterprise.",
    whatIsIt: "PMEGP provides 25% subsidy (35% for SC/ST, women, minorities, and ex-servicemen) on project cost up to ₹50 lakh for manufacturing and ₹20 lakh for services. The rest comes as a bank loan. Subsidy is held as bank security for 3 years and then credited to the entrepreneur. Free EDP training is also provided.",
    benefits: [
      "25% subsidy for general category entrepreneurs",
      "35% subsidy for SC/ST, women, minorities, and ex-servicemen",
      "Manufacturing projects up to ₹50 lakh",
      "Service sector projects up to ₹20 lakh",
      "No collateral for loans up to ₹10 lakh",
      "Free Entrepreneurship Development Programme training",
    ],
    documents: [
      "Aadhaar card and PAN card",
      "Minimum 8th pass certificate for manufacturing projects",
      "Caste certificate if applicable",
      "Detailed project report",
      "Bank statements for 6 months",
    ],
    howToApply: [
      "Register at kviconline.gov.in/pmegpeportal",
      "Fill online application with full project details",
      "Appear for interview at KVIC, KVIB, or DIC office",
      "Submit project report to bank for loan sanction",
      "Complete mandatory EDP training (minimum 2 weeks)",
      "Subsidy released to bank after training completion",
    ],
    eligibilityRules: {
      logic: "AND",
      conditions: [
        { field: "age", operator: "gte", value: 18, label: "Age 18 or above" },
        { field: "occupation", operator: "in", value: ["Self-employed / Small Business", "Unemployed", "Daily Wage / Labour"], label: "Entrepreneur or unemployed person" },
        { field: "income", operator: "lte", value: 800000, label: "Income up to ₹8 lakh" },
      ],
    },
    eligibilityText: "Any Indian citizen aged 18+ setting up a new manufacturing or service micro enterprise",
    officialLink: "https://www.kviconline.gov.in/pmegpeportal",
    applyLink: "https://www.kviconline.gov.in/pmegpeportal/pmegpweb/pmegponline.htm",
  },

  {
    slug: "jan-dhan-yojana",
    name: "Pradhan Mantri Jan Dhan Yojana",
    nameHindi: "प्रधानमंत्री जन धन योजना",
    tagline: "Free zero-balance bank account with ₹2 lakh accident insurance",
    category: "general",
    ministry: "Ministry of Finance",
    icon: "🏦",
    bgColor: "#F0FDF4",
    shortDescription: "Free savings account with zero minimum balance, RuPay debit card, ₹2 lakh accident insurance, ₹30,000 life insurance, and ₹10,000 overdraft — for anyone without a bank account.",
    whatIsIt: "PM Jan Dhan Yojana gives every Indian citizen access to banking. Open a zero-balance account with no minimum balance requirement at any bank. Get a free RuPay debit card with ₹2 lakh accident insurance and ₹30,000 life insurance. After 6 months of good account use, get ₹10,000 overdraft facility. All government DBT benefits credited directly.",
    benefits: [
      "Zero minimum balance — no penalty ever",
      "Free RuPay debit card",
      "₹2 lakh accident insurance cover",
      "₹30,000 life insurance cover",
      "₹10,000 overdraft facility after 6 months",
      "Access to all government direct benefit transfers",
    ],
    documents: [
      "Aadhaar card (sufficient for full KYC)",
      "Or any valid ID and address proof",
      "Passport size photograph",
    ],
    howToApply: [
      "Visit any bank branch or Business Correspondent (BC) point",
      "Fill PMJDY account opening form",
      "Submit Aadhaar card as KYC — account opened immediately",
      "RuPay debit card delivered to your address within 15 days",
    ],
    eligibilityRules: {
      logic: "AND",
      conditions: [
        { field: "age", operator: "gte", value: 10, label: "Age 10 or above" },
      ],
    },
    eligibilityText: "Any Indian citizen aged 10+ who does not already have a bank account",
    officialLink: "https://pmjdy.gov.in",
    applyLink: "https://pmjdy.gov.in/scheme",
  },
];

async function seed() {
  await mongoose.connect(process.env.MONGODB_URI || "mongodb://localhost:27017/yojana_mitra");
  console.log("Connected to MongoDB");

  // Clear existing schemes
  await Scheme.deleteMany({});
  console.log("Cleared existing schemes");

  // Insert all schemes
  const inserted = await Scheme.insertMany(SCHEMES);
  console.log(`✅ Seeded ${inserted.length} schemes successfully`);

  // Show summary
  inserted.forEach((s) => console.log(`  • ${s.name} [${s.category}]`));

  await mongoose.connection.close();
  console.log("\nDone! Run 'npm run dev' to start the server.");
}

seed().catch((err) => {
  console.error("Seed failed:", err.message);
  process.exit(1);
});